services:
  discord-bot:
    build: .
    container_name: discord_bot
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - .:/app
      - /srv:/data/disk-sdb1:ro
      - /hdd/storage:/data/disk-sdc1:ro
    pid: "host"