services:
  discord-bot:
    build: .
    container_name: discord_bot
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - .:/app
      - /Volumes:/Volumes:ro
    pid: "host"