services:
  bot:
    build: .
    image: bot:latest
    container_name: the-herta
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # để chạy docker từ trong container
      - /usr/local/bin/docker:/usr/local/bin/docker
      - .:/app  # mount chính project vào container
      - /home/meou/homelab:/mnt/homelab  # Mount homelab file to container
    working_dir: /app
    tty: true
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
    restart: always

  api:
    build:
      context: ./api  # Chỉ định context là thư mục chứa Dockerfile
    container_name: api
    volumes:
      - .:/app/  # Mount thư mục api vào container
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    working_dir: /app/api
    ports:
      - "20000:20000"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: always

networks:
  internal:
    driver: bridge